### ISSUE TITLE
Problem with Jar files

### ISSUE THREAD

**Issue by islamouahouda** [Will30/MonitorYourLAN#3]
Hello thanks for your project;

the Jar files must be in a folder named "Lib" because we could not find the jar in specific file 
Description	Resource	Path	Location	Type
Project 'MonitorYourLAN' is missing required library: 'D:/MonitorYourLAN/Installation/Librairie pour Eclipse/SNMP4J.jar'	MonitorYourLAN		Build path	Build Path Problem

Thanks

**Comment by Will30** [comment]
Hello,

You can also download this jar at this link:
http://www.snmp4j.org/html/download.html
then you can put into "lib" folder".


This is not the last version of this project, but if you need some info i
can help you...


Regards

2017-06-18 23:39 GMT+02:00 islamouahouda <notifications@github.com>:

**Comment by islamouahouda** [comment]
Thank you it works
